
channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python=3.8.10


  - pip=21.3.1
  - pip:
    # Define pip packages here. 
    # https://pypi.org/
    #- rpa==1.45.0
    #- robotframework-browser==10.0.2
    - rpaframework==11.5.2 # https://rpaframework.org/releasenotes.html
    #- robotframework.archivelibrary
rccPostInstall:
    - rfbrowser init
